apiVersion: v1
kind: Service
metadata:
  name: polling-app
  namespace: polling-app-dev
spec:
  selector:
    app: polling-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
